---
- name: install packages
  apt: pkg={{ item }} state=latest update_cache=yes
  with_items:
    - vim
    - xorg
    - slim
    - icewm
    - icewm-themes
  sudo: yes
  
- name: set vim as default editor
  command: update-alternatives --set editor /usr/bin/vim.basic
  sudo: yes
